name: Build Python Package

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install build tools
      run: |
        python -m pip install --upgrade pip setuptools wheel build

    - name: Build the package
      run: |
        python -m build

    - name: Upload built packages as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/